# Generated by Django 5.1 on 2024-08-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='Achievement',
            field=models.ManyToManyField(blank=True, to='accounts.achievement'),
        ),
    ]
