# Generated by Django 5.1 on 2024-12-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Achievement',
            new_name='achievements',
        ),
        migrations.AddField(
            model_name='profile',
            name='family_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='given_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.URLField(blank=True),
        ),
    ]
