# Generated by Django 5.1 on 2024-09-05 23:08

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='body',
        ),
        migrations.RemoveField(
            model_name='usercard',
            name='last_shown',
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercard',
            name='first_show',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cards',
            field=models.ManyToManyField(related_name='tags', to='clusters.card'),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='next_show',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
