# Generated by Django 5.1 on 2024-10-12 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_deck_is_public_remove_deck_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercard',
            name='first_show',
        ),
        migrations.RemoveField(
            model_name='usercard',
            name='next_show',
        ),
        migrations.RemoveField(
            model_name='userdeck',
            name='first_show',
        ),
        migrations.RemoveField(
            model_name='userdeck',
            name='next_show',
        ),
    ]
